DEF=test
EXT=test
TESTDIR=.
KOMPILE_BACKEND=llvm
KOMPILE_FLAGS+=--enable-search --non-deterministic-cooling division --syntax-module TEST
KRUN_FLAGS+=--search

include ../../../include/kframework/ktest.mak
